//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.4927
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace SISAR.WebAnimation.User {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="User.SW_UsuarioSoap")]
    public interface SW_UsuarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SelectAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginSelectAll(System.AsyncCallback callback, object asyncState);
        
        SISAR.WebAnimation.User.ArrayOfXElement EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Insert", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginInsert(SISAR.WebAnimation.User.T_Usuario _usuario, System.AsyncCallback callback, object asyncState);
        
        string EndInsert(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginUpdate(SISAR.WebAnimation.User.T_Usuario _usuario, System.AsyncCallback callback, object asyncState);
        
        string EndUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginDelete(int _idUsuario, System.AsyncCallback callback, object asyncState);
        
        string EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginAuthenticateUser(int _idUsuario, string password, System.AsyncCallback callback, object asyncState);
        
        bool EndAuthenticateUser(System.IAsyncResult result);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class T_Usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_UsuarioField;
        
        private string nombresField;
        
        private string apellidosField;
        
        private string telefonoField;
        
        private string direccionField;
        
        private string emailField;
        
        private System.DateTime fecha_RegistroField;
        
        private string contraseñaField;
        
        private string estadoField;
        
        private int id_SucursalField;
        
        private int id_PerfilField;
        
        private System.DateTime fecha_NacimientoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id_Usuario {
            get {
                return this.id_UsuarioField;
            }
            set {
                this.id_UsuarioField = value;
                this.RaisePropertyChanged("Id_Usuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("Nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("Apellidos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("Telefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime Fecha_Registro {
            get {
                return this.fecha_RegistroField;
            }
            set {
                this.fecha_RegistroField = value;
                this.RaisePropertyChanged("Fecha_Registro");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
                this.RaisePropertyChanged("Contraseña");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int Id_Sucursal {
            get {
                return this.id_SucursalField;
            }
            set {
                this.id_SucursalField = value;
                this.RaisePropertyChanged("Id_Sucursal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Id_Perfil {
            get {
                return this.id_PerfilField;
            }
            set {
                this.id_PerfilField = value;
                this.RaisePropertyChanged("Id_Perfil");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime Fecha_Nacimiento {
            get {
                return this.fecha_NacimientoField;
            }
            set {
                this.fecha_NacimientoField = value;
                this.RaisePropertyChanged("Fecha_Nacimiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SW_UsuarioSoapChannel : SISAR.WebAnimation.User.SW_UsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SelectAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SISAR.WebAnimation.User.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SISAR.WebAnimation.User.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class InsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SW_UsuarioSoapClient : System.ServiceModel.ClientBase<SISAR.WebAnimation.User.SW_UsuarioSoap>, SISAR.WebAnimation.User.SW_UsuarioSoap {
        
        private BeginOperationDelegate onBeginSelectAllDelegate;
        
        private EndOperationDelegate onEndSelectAllDelegate;
        
        private System.Threading.SendOrPostCallback onSelectAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertDelegate;
        
        private EndOperationDelegate onEndInsertDelegate;
        
        private System.Threading.SendOrPostCallback onInsertCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDelegate;
        
        private EndOperationDelegate onEndUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginAuthenticateUserDelegate;
        
        private EndOperationDelegate onEndAuthenticateUserDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SW_UsuarioSoapClient() {
        }
        
        public SW_UsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SW_UsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SW_UsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SW_UsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SelectAllCompletedEventArgs> SelectAllCompleted;
        
        public event System.EventHandler<InsertCompletedEventArgs> InsertCompleted;
        
        public event System.EventHandler<UpdateCompletedEventArgs> UpdateCompleted;
        
        public event System.EventHandler<DeleteCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<AuthenticateUserCompletedEventArgs> AuthenticateUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioSoap.BeginSelectAll(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectAll(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SISAR.WebAnimation.User.ArrayOfXElement SISAR.WebAnimation.User.SW_UsuarioSoap.EndSelectAll(System.IAsyncResult result) {
            return base.Channel.EndSelectAll(result);
        }
        
        private System.IAsyncResult OnBeginSelectAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).BeginSelectAll(callback, asyncState);
        }
        
        private object[] OnEndSelectAll(System.IAsyncResult result) {
            SISAR.WebAnimation.User.ArrayOfXElement retVal = ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).EndSelectAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectAllCompleted(object state) {
            if ((this.SelectAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectAllCompleted(this, new SelectAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectAllAsync() {
            this.SelectAllAsync(null);
        }
        
        public void SelectAllAsync(object userState) {
            if ((this.onBeginSelectAllDelegate == null)) {
                this.onBeginSelectAllDelegate = new BeginOperationDelegate(this.OnBeginSelectAll);
            }
            if ((this.onEndSelectAllDelegate == null)) {
                this.onEndSelectAllDelegate = new EndOperationDelegate(this.OnEndSelectAll);
            }
            if ((this.onSelectAllCompletedDelegate == null)) {
                this.onSelectAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectAllCompleted);
            }
            base.InvokeAsync(this.onBeginSelectAllDelegate, null, this.onEndSelectAllDelegate, this.onSelectAllCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioSoap.BeginInsert(SISAR.WebAnimation.User.T_Usuario _usuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsert(_usuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SISAR.WebAnimation.User.SW_UsuarioSoap.EndInsert(System.IAsyncResult result) {
            return base.Channel.EndInsert(result);
        }
        
        private System.IAsyncResult OnBeginInsert(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SISAR.WebAnimation.User.T_Usuario _usuario = ((SISAR.WebAnimation.User.T_Usuario)(inValues[0]));
            return ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).BeginInsert(_usuario, callback, asyncState);
        }
        
        private object[] OnEndInsert(System.IAsyncResult result) {
            string retVal = ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).EndInsert(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertCompleted(object state) {
            if ((this.InsertCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertCompleted(this, new InsertCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertAsync(SISAR.WebAnimation.User.T_Usuario _usuario) {
            this.InsertAsync(_usuario, null);
        }
        
        public void InsertAsync(SISAR.WebAnimation.User.T_Usuario _usuario, object userState) {
            if ((this.onBeginInsertDelegate == null)) {
                this.onBeginInsertDelegate = new BeginOperationDelegate(this.OnBeginInsert);
            }
            if ((this.onEndInsertDelegate == null)) {
                this.onEndInsertDelegate = new EndOperationDelegate(this.OnEndInsert);
            }
            if ((this.onInsertCompletedDelegate == null)) {
                this.onInsertCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDelegate, new object[] {
                        _usuario}, this.onEndInsertDelegate, this.onInsertCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioSoap.BeginUpdate(SISAR.WebAnimation.User.T_Usuario _usuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdate(_usuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SISAR.WebAnimation.User.SW_UsuarioSoap.EndUpdate(System.IAsyncResult result) {
            return base.Channel.EndUpdate(result);
        }
        
        private System.IAsyncResult OnBeginUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SISAR.WebAnimation.User.T_Usuario _usuario = ((SISAR.WebAnimation.User.T_Usuario)(inValues[0]));
            return ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).BeginUpdate(_usuario, callback, asyncState);
        }
        
        private object[] OnEndUpdate(System.IAsyncResult result) {
            string retVal = ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).EndUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateCompleted(object state) {
            if ((this.UpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateAsync(SISAR.WebAnimation.User.T_Usuario _usuario) {
            this.UpdateAsync(_usuario, null);
        }
        
        public void UpdateAsync(SISAR.WebAnimation.User.T_Usuario _usuario, object userState) {
            if ((this.onBeginUpdateDelegate == null)) {
                this.onBeginUpdateDelegate = new BeginOperationDelegate(this.OnBeginUpdate);
            }
            if ((this.onEndUpdateDelegate == null)) {
                this.onEndUpdateDelegate = new EndOperationDelegate(this.OnEndUpdate);
            }
            if ((this.onUpdateCompletedDelegate == null)) {
                this.onUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDelegate, new object[] {
                        _usuario}, this.onEndUpdateDelegate, this.onUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioSoap.BeginDelete(int _idUsuario, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(_idUsuario, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SISAR.WebAnimation.User.SW_UsuarioSoap.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _idUsuario = ((int)(inValues[0]));
            return ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).BeginDelete(_idUsuario, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            string retVal = ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).EndDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(int _idUsuario) {
            this.DeleteAsync(_idUsuario, null);
        }
        
        public void DeleteAsync(int _idUsuario, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        _idUsuario}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioSoap.BeginAuthenticateUser(int _idUsuario, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticateUser(_idUsuario, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SISAR.WebAnimation.User.SW_UsuarioSoap.EndAuthenticateUser(System.IAsyncResult result) {
            return base.Channel.EndAuthenticateUser(result);
        }
        
        private System.IAsyncResult OnBeginAuthenticateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _idUsuario = ((int)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).BeginAuthenticateUser(_idUsuario, password, callback, asyncState);
        }
        
        private object[] OnEndAuthenticateUser(System.IAsyncResult result) {
            bool retVal = ((SISAR.WebAnimation.User.SW_UsuarioSoap)(this)).EndAuthenticateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateUserCompleted(object state) {
            if ((this.AuthenticateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateUserAsync(int _idUsuario, string password) {
            this.AuthenticateUserAsync(_idUsuario, password, null);
        }
        
        public void AuthenticateUserAsync(int _idUsuario, string password, object userState) {
            if ((this.onBeginAuthenticateUserDelegate == null)) {
                this.onBeginAuthenticateUserDelegate = new BeginOperationDelegate(this.OnBeginAuthenticateUser);
            }
            if ((this.onEndAuthenticateUserDelegate == null)) {
                this.onEndAuthenticateUserDelegate = new EndOperationDelegate(this.OnEndAuthenticateUser);
            }
            if ((this.onAuthenticateUserCompletedDelegate == null)) {
                this.onAuthenticateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateUserDelegate, new object[] {
                        _idUsuario,
                        password}, this.onEndAuthenticateUserDelegate, this.onAuthenticateUserCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SISAR.WebAnimation.User.SW_UsuarioSoap CreateChannel() {
            return new SW_UsuarioSoapClientChannel(this);
        }
        
        private class SW_UsuarioSoapClientChannel : ChannelBase<SISAR.WebAnimation.User.SW_UsuarioSoap>, SISAR.WebAnimation.User.SW_UsuarioSoap {
            
            public SW_UsuarioSoapClientChannel(System.ServiceModel.ClientBase<SISAR.WebAnimation.User.SW_UsuarioSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSelectAll(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("SelectAll", _args, callback, asyncState);
                return _result;
            }
            
            public SISAR.WebAnimation.User.ArrayOfXElement EndSelectAll(System.IAsyncResult result) {
                object[] _args = new object[0];
                SISAR.WebAnimation.User.ArrayOfXElement _result = ((SISAR.WebAnimation.User.ArrayOfXElement)(base.EndInvoke("SelectAll", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsert(SISAR.WebAnimation.User.T_Usuario _usuario, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _usuario;
                System.IAsyncResult _result = base.BeginInvoke("Insert", _args, callback, asyncState);
                return _result;
            }
            
            public string EndInsert(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Insert", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdate(SISAR.WebAnimation.User.T_Usuario _usuario, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _usuario;
                System.IAsyncResult _result = base.BeginInvoke("Update", _args, callback, asyncState);
                return _result;
            }
            
            public string EndUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Update", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDelete(int _idUsuario, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _idUsuario;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public string EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Delete", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAuthenticateUser(int _idUsuario, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = _idUsuario;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("AuthenticateUser", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndAuthenticateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("AuthenticateUser", _args, result)));
                return _result;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="User.SW_UsuarioHttpGet")]
    public interface SW_UsuarioHttpGet {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SW_UsuarioHttpGet/SelectAllRequest", ReplyAction="http://tempuri.org/SW_UsuarioHttpGet/SelectAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginSelectAll(SISAR.WebAnimation.User.SelectAllRequest request, System.AsyncCallback callback, object asyncState);
        
        SISAR.WebAnimation.User.SelectAllResponse EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SW_UsuarioHttpGet/DeleteRequest", ReplyAction="http://tempuri.org/SW_UsuarioHttpGet/DeleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginDelete(SISAR.WebAnimation.User.DeleteRequest request, System.AsyncCallback callback, object asyncState);
        
        SISAR.WebAnimation.User.DeleteResponse EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SW_UsuarioHttpGet/AuthenticateUserRequest", ReplyAction="http://tempuri.org/SW_UsuarioHttpGet/AuthenticateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginAuthenticateUser(SISAR.WebAnimation.User.AuthenticateUserRequest request, System.AsyncCallback callback, object asyncState);
        
        SISAR.WebAnimation.User.AuthenticateUserResponse EndAuthenticateUser(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllRequest {
        
        public SelectAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SISAR.WebAnimation.User.ArrayOfXElement DataSet;
        
        public SelectAllResponse() {
        }
        
        public SelectAllResponse(SISAR.WebAnimation.User.ArrayOfXElement DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _idUsuario;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(string _idUsuario) {
            this._idUsuario = _idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public DeleteResponse() {
        }
        
        public DeleteResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(string _idUsuario, string password) {
            this._idUsuario = _idUsuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool boolean;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(bool boolean) {
            this.boolean = boolean;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SW_UsuarioHttpGetChannel : SISAR.WebAnimation.User.SW_UsuarioHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SelectAllCompletedEventArgs1 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectAllCompletedEventArgs1(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SISAR.WebAnimation.User.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SISAR.WebAnimation.User.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DeleteCompletedEventArgs1 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteCompletedEventArgs1(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AuthenticateUserCompletedEventArgs1 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateUserCompletedEventArgs1(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SW_UsuarioHttpGetClient : System.ServiceModel.ClientBase<SISAR.WebAnimation.User.SW_UsuarioHttpGet>, SISAR.WebAnimation.User.SW_UsuarioHttpGet {
        
        private BeginOperationDelegate onBeginSelectAllDelegate;
        
        private EndOperationDelegate onEndSelectAllDelegate;
        
        private System.Threading.SendOrPostCallback onSelectAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginAuthenticateUserDelegate;
        
        private EndOperationDelegate onEndAuthenticateUserDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SW_UsuarioHttpGetClient() {
        }
        
        public SW_UsuarioHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SW_UsuarioHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SW_UsuarioHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SW_UsuarioHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SelectAllCompletedEventArgs1> SelectAllCompleted;
        
        public event System.EventHandler<DeleteCompletedEventArgs1> DeleteCompleted;
        
        public event System.EventHandler<AuthenticateUserCompletedEventArgs1> AuthenticateUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioHttpGet.BeginSelectAll(SISAR.WebAnimation.User.SelectAllRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectAll(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSelectAll(System.AsyncCallback callback, object asyncState) {
            SISAR.WebAnimation.User.SelectAllRequest inValue = new SISAR.WebAnimation.User.SelectAllRequest();
            return ((SISAR.WebAnimation.User.SW_UsuarioHttpGet)(this)).BeginSelectAll(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SISAR.WebAnimation.User.SelectAllResponse SISAR.WebAnimation.User.SW_UsuarioHttpGet.EndSelectAll(System.IAsyncResult result) {
            return base.Channel.EndSelectAll(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private SISAR.WebAnimation.User.ArrayOfXElement EndSelectAll(System.IAsyncResult result) {
            SISAR.WebAnimation.User.SelectAllResponse retVal = ((SISAR.WebAnimation.User.SW_UsuarioHttpGet)(this)).EndSelectAll(result);
            return retVal.DataSet;
        }
        
        private System.IAsyncResult OnBeginSelectAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginSelectAll(callback, asyncState);
        }
        
        private object[] OnEndSelectAll(System.IAsyncResult result) {
            SISAR.WebAnimation.User.ArrayOfXElement retVal = this.EndSelectAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectAllCompleted(object state) {
            if ((this.SelectAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectAllCompleted(this, new SelectAllCompletedEventArgs1(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectAllAsync() {
            this.SelectAllAsync(null);
        }
        
        public void SelectAllAsync(object userState) {
            if ((this.onBeginSelectAllDelegate == null)) {
                this.onBeginSelectAllDelegate = new BeginOperationDelegate(this.OnBeginSelectAll);
            }
            if ((this.onEndSelectAllDelegate == null)) {
                this.onEndSelectAllDelegate = new EndOperationDelegate(this.OnEndSelectAll);
            }
            if ((this.onSelectAllCompletedDelegate == null)) {
                this.onSelectAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectAllCompleted);
            }
            base.InvokeAsync(this.onBeginSelectAllDelegate, null, this.onEndSelectAllDelegate, this.onSelectAllCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioHttpGet.BeginDelete(SISAR.WebAnimation.User.DeleteRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginDelete(string _idUsuario, System.AsyncCallback callback, object asyncState) {
            SISAR.WebAnimation.User.DeleteRequest inValue = new SISAR.WebAnimation.User.DeleteRequest();
            inValue._idUsuario = _idUsuario;
            return ((SISAR.WebAnimation.User.SW_UsuarioHttpGet)(this)).BeginDelete(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SISAR.WebAnimation.User.DeleteResponse SISAR.WebAnimation.User.SW_UsuarioHttpGet.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndDelete(System.IAsyncResult result) {
            SISAR.WebAnimation.User.DeleteResponse retVal = ((SISAR.WebAnimation.User.SW_UsuarioHttpGet)(this)).EndDelete(result);
            return retVal.@string;
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _idUsuario = ((string)(inValues[0]));
            return this.BeginDelete(_idUsuario, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            string retVal = this.EndDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs1(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(string _idUsuario) {
            this.DeleteAsync(_idUsuario, null);
        }
        
        public void DeleteAsync(string _idUsuario, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        _idUsuario}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioHttpGet.BeginAuthenticateUser(SISAR.WebAnimation.User.AuthenticateUserRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticateUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAuthenticateUser(string _idUsuario, string password, System.AsyncCallback callback, object asyncState) {
            SISAR.WebAnimation.User.AuthenticateUserRequest inValue = new SISAR.WebAnimation.User.AuthenticateUserRequest();
            inValue._idUsuario = _idUsuario;
            inValue.password = password;
            return ((SISAR.WebAnimation.User.SW_UsuarioHttpGet)(this)).BeginAuthenticateUser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SISAR.WebAnimation.User.AuthenticateUserResponse SISAR.WebAnimation.User.SW_UsuarioHttpGet.EndAuthenticateUser(System.IAsyncResult result) {
            return base.Channel.EndAuthenticateUser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndAuthenticateUser(System.IAsyncResult result) {
            SISAR.WebAnimation.User.AuthenticateUserResponse retVal = ((SISAR.WebAnimation.User.SW_UsuarioHttpGet)(this)).EndAuthenticateUser(result);
            return retVal.boolean;
        }
        
        private System.IAsyncResult OnBeginAuthenticateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _idUsuario = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginAuthenticateUser(_idUsuario, password, callback, asyncState);
        }
        
        private object[] OnEndAuthenticateUser(System.IAsyncResult result) {
            bool retVal = this.EndAuthenticateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateUserCompleted(object state) {
            if ((this.AuthenticateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs1(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateUserAsync(string _idUsuario, string password) {
            this.AuthenticateUserAsync(_idUsuario, password, null);
        }
        
        public void AuthenticateUserAsync(string _idUsuario, string password, object userState) {
            if ((this.onBeginAuthenticateUserDelegate == null)) {
                this.onBeginAuthenticateUserDelegate = new BeginOperationDelegate(this.OnBeginAuthenticateUser);
            }
            if ((this.onEndAuthenticateUserDelegate == null)) {
                this.onEndAuthenticateUserDelegate = new EndOperationDelegate(this.OnEndAuthenticateUser);
            }
            if ((this.onAuthenticateUserCompletedDelegate == null)) {
                this.onAuthenticateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateUserDelegate, new object[] {
                        _idUsuario,
                        password}, this.onEndAuthenticateUserDelegate, this.onAuthenticateUserCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SISAR.WebAnimation.User.SW_UsuarioHttpGet CreateChannel() {
            return new SW_UsuarioHttpGetClientChannel(this);
        }
        
        private class SW_UsuarioHttpGetClientChannel : ChannelBase<SISAR.WebAnimation.User.SW_UsuarioHttpGet>, SISAR.WebAnimation.User.SW_UsuarioHttpGet {
            
            public SW_UsuarioHttpGetClientChannel(System.ServiceModel.ClientBase<SISAR.WebAnimation.User.SW_UsuarioHttpGet> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSelectAll(SISAR.WebAnimation.User.SelectAllRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SelectAll", _args, callback, asyncState);
                return _result;
            }
            
            public SISAR.WebAnimation.User.SelectAllResponse EndSelectAll(System.IAsyncResult result) {
                object[] _args = new object[0];
                SISAR.WebAnimation.User.SelectAllResponse _result = ((SISAR.WebAnimation.User.SelectAllResponse)(base.EndInvoke("SelectAll", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDelete(SISAR.WebAnimation.User.DeleteRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public SISAR.WebAnimation.User.DeleteResponse EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                SISAR.WebAnimation.User.DeleteResponse _result = ((SISAR.WebAnimation.User.DeleteResponse)(base.EndInvoke("Delete", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAuthenticateUser(SISAR.WebAnimation.User.AuthenticateUserRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AuthenticateUser", _args, callback, asyncState);
                return _result;
            }
            
            public SISAR.WebAnimation.User.AuthenticateUserResponse EndAuthenticateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                SISAR.WebAnimation.User.AuthenticateUserResponse _result = ((SISAR.WebAnimation.User.AuthenticateUserResponse)(base.EndInvoke("AuthenticateUser", _args, result)));
                return _result;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="User.SW_UsuarioHttpPost")]
    public interface SW_UsuarioHttpPost {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SW_UsuarioHttpPost/SelectAllRequest", ReplyAction="http://tempuri.org/SW_UsuarioHttpPost/SelectAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginSelectAll(SISAR.WebAnimation.User.SelectAllRequest1 request, System.AsyncCallback callback, object asyncState);
        
        SISAR.WebAnimation.User.SelectAllResponse1 EndSelectAll(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SW_UsuarioHttpPost/DeleteRequest", ReplyAction="http://tempuri.org/SW_UsuarioHttpPost/DeleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginDelete(SISAR.WebAnimation.User.DeleteRequest1 request, System.AsyncCallback callback, object asyncState);
        
        SISAR.WebAnimation.User.DeleteResponse1 EndDelete(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SW_UsuarioHttpPost/AuthenticateUserRequest", ReplyAction="http://tempuri.org/SW_UsuarioHttpPost/AuthenticateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginAuthenticateUser(SISAR.WebAnimation.User.AuthenticateUserRequest1 request, System.AsyncCallback callback, object asyncState);
        
        SISAR.WebAnimation.User.AuthenticateUserResponse1 EndAuthenticateUser(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllRequest1 {
        
        public SelectAllRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectAllResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SISAR.WebAnimation.User.ArrayOfXElement DataSet;
        
        public SelectAllResponse1() {
        }
        
        public SelectAllResponse1(SISAR.WebAnimation.User.ArrayOfXElement DataSet) {
            this.DataSet = DataSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _idUsuario;
        
        public DeleteRequest1() {
        }
        
        public DeleteRequest1(string _idUsuario) {
            this._idUsuario = _idUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public DeleteResponse1() {
        }
        
        public DeleteResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string _idUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public AuthenticateUserRequest1() {
        }
        
        public AuthenticateUserRequest1(string _idUsuario, string password) {
            this._idUsuario = _idUsuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool boolean;
        
        public AuthenticateUserResponse1() {
        }
        
        public AuthenticateUserResponse1(bool boolean) {
            this.boolean = boolean;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SW_UsuarioHttpPostChannel : SISAR.WebAnimation.User.SW_UsuarioHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SelectAllCompletedEventArgs2 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SelectAllCompletedEventArgs2(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SISAR.WebAnimation.User.ArrayOfXElement Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SISAR.WebAnimation.User.ArrayOfXElement)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DeleteCompletedEventArgs2 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteCompletedEventArgs2(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AuthenticateUserCompletedEventArgs2 : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateUserCompletedEventArgs2(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SW_UsuarioHttpPostClient : System.ServiceModel.ClientBase<SISAR.WebAnimation.User.SW_UsuarioHttpPost>, SISAR.WebAnimation.User.SW_UsuarioHttpPost {
        
        private BeginOperationDelegate onBeginSelectAllDelegate;
        
        private EndOperationDelegate onEndSelectAllDelegate;
        
        private System.Threading.SendOrPostCallback onSelectAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginAuthenticateUserDelegate;
        
        private EndOperationDelegate onEndAuthenticateUserDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SW_UsuarioHttpPostClient() {
        }
        
        public SW_UsuarioHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SW_UsuarioHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SW_UsuarioHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SW_UsuarioHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SelectAllCompletedEventArgs2> SelectAllCompleted;
        
        public event System.EventHandler<DeleteCompletedEventArgs2> DeleteCompleted;
        
        public event System.EventHandler<AuthenticateUserCompletedEventArgs2> AuthenticateUserCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioHttpPost.BeginSelectAll(SISAR.WebAnimation.User.SelectAllRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSelectAll(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSelectAll(System.AsyncCallback callback, object asyncState) {
            SISAR.WebAnimation.User.SelectAllRequest1 inValue = new SISAR.WebAnimation.User.SelectAllRequest1();
            return ((SISAR.WebAnimation.User.SW_UsuarioHttpPost)(this)).BeginSelectAll(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SISAR.WebAnimation.User.SelectAllResponse1 SISAR.WebAnimation.User.SW_UsuarioHttpPost.EndSelectAll(System.IAsyncResult result) {
            return base.Channel.EndSelectAll(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private SISAR.WebAnimation.User.ArrayOfXElement EndSelectAll(System.IAsyncResult result) {
            SISAR.WebAnimation.User.SelectAllResponse1 retVal = ((SISAR.WebAnimation.User.SW_UsuarioHttpPost)(this)).EndSelectAll(result);
            return retVal.DataSet;
        }
        
        private System.IAsyncResult OnBeginSelectAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginSelectAll(callback, asyncState);
        }
        
        private object[] OnEndSelectAll(System.IAsyncResult result) {
            SISAR.WebAnimation.User.ArrayOfXElement retVal = this.EndSelectAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSelectAllCompleted(object state) {
            if ((this.SelectAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SelectAllCompleted(this, new SelectAllCompletedEventArgs2(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SelectAllAsync() {
            this.SelectAllAsync(null);
        }
        
        public void SelectAllAsync(object userState) {
            if ((this.onBeginSelectAllDelegate == null)) {
                this.onBeginSelectAllDelegate = new BeginOperationDelegate(this.OnBeginSelectAll);
            }
            if ((this.onEndSelectAllDelegate == null)) {
                this.onEndSelectAllDelegate = new EndOperationDelegate(this.OnEndSelectAll);
            }
            if ((this.onSelectAllCompletedDelegate == null)) {
                this.onSelectAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSelectAllCompleted);
            }
            base.InvokeAsync(this.onBeginSelectAllDelegate, null, this.onEndSelectAllDelegate, this.onSelectAllCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioHttpPost.BeginDelete(SISAR.WebAnimation.User.DeleteRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginDelete(string _idUsuario, System.AsyncCallback callback, object asyncState) {
            SISAR.WebAnimation.User.DeleteRequest1 inValue = new SISAR.WebAnimation.User.DeleteRequest1();
            inValue._idUsuario = _idUsuario;
            return ((SISAR.WebAnimation.User.SW_UsuarioHttpPost)(this)).BeginDelete(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SISAR.WebAnimation.User.DeleteResponse1 SISAR.WebAnimation.User.SW_UsuarioHttpPost.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndDelete(System.IAsyncResult result) {
            SISAR.WebAnimation.User.DeleteResponse1 retVal = ((SISAR.WebAnimation.User.SW_UsuarioHttpPost)(this)).EndDelete(result);
            return retVal.@string;
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _idUsuario = ((string)(inValues[0]));
            return this.BeginDelete(_idUsuario, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            string retVal = this.EndDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs2(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(string _idUsuario) {
            this.DeleteAsync(_idUsuario, null);
        }
        
        public void DeleteAsync(string _idUsuario, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        _idUsuario}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.WebAnimation.User.SW_UsuarioHttpPost.BeginAuthenticateUser(SISAR.WebAnimation.User.AuthenticateUserRequest1 request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticateUser(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAuthenticateUser(string _idUsuario, string password, System.AsyncCallback callback, object asyncState) {
            SISAR.WebAnimation.User.AuthenticateUserRequest1 inValue = new SISAR.WebAnimation.User.AuthenticateUserRequest1();
            inValue._idUsuario = _idUsuario;
            inValue.password = password;
            return ((SISAR.WebAnimation.User.SW_UsuarioHttpPost)(this)).BeginAuthenticateUser(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SISAR.WebAnimation.User.AuthenticateUserResponse1 SISAR.WebAnimation.User.SW_UsuarioHttpPost.EndAuthenticateUser(System.IAsyncResult result) {
            return base.Channel.EndAuthenticateUser(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool EndAuthenticateUser(System.IAsyncResult result) {
            SISAR.WebAnimation.User.AuthenticateUserResponse1 retVal = ((SISAR.WebAnimation.User.SW_UsuarioHttpPost)(this)).EndAuthenticateUser(result);
            return retVal.boolean;
        }
        
        private System.IAsyncResult OnBeginAuthenticateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _idUsuario = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return this.BeginAuthenticateUser(_idUsuario, password, callback, asyncState);
        }
        
        private object[] OnEndAuthenticateUser(System.IAsyncResult result) {
            bool retVal = this.EndAuthenticateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateUserCompleted(object state) {
            if ((this.AuthenticateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs2(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateUserAsync(string _idUsuario, string password) {
            this.AuthenticateUserAsync(_idUsuario, password, null);
        }
        
        public void AuthenticateUserAsync(string _idUsuario, string password, object userState) {
            if ((this.onBeginAuthenticateUserDelegate == null)) {
                this.onBeginAuthenticateUserDelegate = new BeginOperationDelegate(this.OnBeginAuthenticateUser);
            }
            if ((this.onEndAuthenticateUserDelegate == null)) {
                this.onEndAuthenticateUserDelegate = new EndOperationDelegate(this.OnEndAuthenticateUser);
            }
            if ((this.onAuthenticateUserCompletedDelegate == null)) {
                this.onAuthenticateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateUserDelegate, new object[] {
                        _idUsuario,
                        password}, this.onEndAuthenticateUserDelegate, this.onAuthenticateUserCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SISAR.WebAnimation.User.SW_UsuarioHttpPost CreateChannel() {
            return new SW_UsuarioHttpPostClientChannel(this);
        }
        
        private class SW_UsuarioHttpPostClientChannel : ChannelBase<SISAR.WebAnimation.User.SW_UsuarioHttpPost>, SISAR.WebAnimation.User.SW_UsuarioHttpPost {
            
            public SW_UsuarioHttpPostClientChannel(System.ServiceModel.ClientBase<SISAR.WebAnimation.User.SW_UsuarioHttpPost> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSelectAll(SISAR.WebAnimation.User.SelectAllRequest1 request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SelectAll", _args, callback, asyncState);
                return _result;
            }
            
            public SISAR.WebAnimation.User.SelectAllResponse1 EndSelectAll(System.IAsyncResult result) {
                object[] _args = new object[0];
                SISAR.WebAnimation.User.SelectAllResponse1 _result = ((SISAR.WebAnimation.User.SelectAllResponse1)(base.EndInvoke("SelectAll", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDelete(SISAR.WebAnimation.User.DeleteRequest1 request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public SISAR.WebAnimation.User.DeleteResponse1 EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                SISAR.WebAnimation.User.DeleteResponse1 _result = ((SISAR.WebAnimation.User.DeleteResponse1)(base.EndInvoke("Delete", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAuthenticateUser(SISAR.WebAnimation.User.AuthenticateUserRequest1 request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AuthenticateUser", _args, callback, asyncState);
                return _result;
            }
            
            public SISAR.WebAnimation.User.AuthenticateUserResponse1 EndAuthenticateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                SISAR.WebAnimation.User.AuthenticateUserResponse1 _result = ((SISAR.WebAnimation.User.AuthenticateUserResponse1)(base.EndInvoke("AuthenticateUser", _args, result)));
                return _result;
            }
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Silverlight.ServiceReference", "3.0.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement() {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes {
            get {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema() {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer) {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            ) {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader) {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            ) {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element)) {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else {
                    reader.Skip();
                }
            }
        }
    }
}
