//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.3603
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace SISAR.Web.ReservaService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Reserva", Namespace="http://schemas.datacontract.org/2004/07/SISAR.WebApplication.ReserveReference")]
    public partial class T_Reserva : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fecha_ReservaFieldField;
        
        private int id_ReservaFieldField;
        
        private int id_UsuarioFieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime fecha_ReservaField {
            get {
                return this.fecha_ReservaFieldField;
            }
            set {
                if ((this.fecha_ReservaFieldField.Equals(value) != true)) {
                    this.fecha_ReservaFieldField = value;
                    this.RaisePropertyChanged("fecha_ReservaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_ReservaField {
            get {
                return this.id_ReservaFieldField;
            }
            set {
                if ((this.id_ReservaFieldField.Equals(value) != true)) {
                    this.id_ReservaFieldField = value;
                    this.RaisePropertyChanged("id_ReservaField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_UsuarioField {
            get {
                return this.id_UsuarioFieldField;
            }
            set {
                if ((this.id_UsuarioFieldField.Equals(value) != true)) {
                    this.id_UsuarioFieldField = value;
                    this.RaisePropertyChanged("id_UsuarioField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ReservaService.ReservaService")]
    public interface ReservaService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:ReservaService/RegistrarReserva", ReplyAction="urn:ReservaService/RegistrarReservaResponse")]
        System.IAsyncResult BeginRegistrarReserva(SISAR.Web.ReservaService.T_Reserva _reservacion, System.AsyncCallback callback, object asyncState);
        
        string EndRegistrarReserva(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ReservaServiceChannel : SISAR.Web.ReservaService.ReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class RegistrarReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegistrarReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ReservaServiceClient : System.ServiceModel.ClientBase<SISAR.Web.ReservaService.ReservaService>, SISAR.Web.ReservaService.ReservaService {
        
        private BeginOperationDelegate onBeginRegistrarReservaDelegate;
        
        private EndOperationDelegate onEndRegistrarReservaDelegate;
        
        private System.Threading.SendOrPostCallback onRegistrarReservaCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ReservaServiceClient() {
        }
        
        public ReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("No se puede establecer el objeto CookieContainer. Asegúrese de que el enlace cont" +
                            "iene un objeto HttpCookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RegistrarReservaCompletedEventArgs> RegistrarReservaCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SISAR.Web.ReservaService.ReservaService.BeginRegistrarReserva(SISAR.Web.ReservaService.T_Reserva _reservacion, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegistrarReserva(_reservacion, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SISAR.Web.ReservaService.ReservaService.EndRegistrarReserva(System.IAsyncResult result) {
            return base.Channel.EndRegistrarReserva(result);
        }
        
        private System.IAsyncResult OnBeginRegistrarReserva(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SISAR.Web.ReservaService.T_Reserva _reservacion = ((SISAR.Web.ReservaService.T_Reserva)(inValues[0]));
            return ((SISAR.Web.ReservaService.ReservaService)(this)).BeginRegistrarReserva(_reservacion, callback, asyncState);
        }
        
        private object[] OnEndRegistrarReserva(System.IAsyncResult result) {
            string retVal = ((SISAR.Web.ReservaService.ReservaService)(this)).EndRegistrarReserva(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegistrarReservaCompleted(object state) {
            if ((this.RegistrarReservaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegistrarReservaCompleted(this, new RegistrarReservaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegistrarReservaAsync(SISAR.Web.ReservaService.T_Reserva _reservacion) {
            this.RegistrarReservaAsync(_reservacion, null);
        }
        
        public void RegistrarReservaAsync(SISAR.Web.ReservaService.T_Reserva _reservacion, object userState) {
            if ((this.onBeginRegistrarReservaDelegate == null)) {
                this.onBeginRegistrarReservaDelegate = new BeginOperationDelegate(this.OnBeginRegistrarReserva);
            }
            if ((this.onEndRegistrarReservaDelegate == null)) {
                this.onEndRegistrarReservaDelegate = new EndOperationDelegate(this.OnEndRegistrarReserva);
            }
            if ((this.onRegistrarReservaCompletedDelegate == null)) {
                this.onRegistrarReservaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegistrarReservaCompleted);
            }
            base.InvokeAsync(this.onBeginRegistrarReservaDelegate, new object[] {
                        _reservacion}, this.onEndRegistrarReservaDelegate, this.onRegistrarReservaCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SISAR.Web.ReservaService.ReservaService CreateChannel() {
            return new ReservaServiceClientChannel(this);
        }
        
        private class ReservaServiceClientChannel : ChannelBase<SISAR.Web.ReservaService.ReservaService>, SISAR.Web.ReservaService.ReservaService {
            
            public ReservaServiceClientChannel(System.ServiceModel.ClientBase<SISAR.Web.ReservaService.ReservaService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegistrarReserva(SISAR.Web.ReservaService.T_Reserva _reservacion, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _reservacion;
                System.IAsyncResult _result = base.BeginInvoke("RegistrarReserva", _args, callback, asyncState);
                return _result;
            }
            
            public string EndRegistrarReserva(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("RegistrarReserva", _args, result)));
                return _result;
            }
        }
    }
}
